import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'id' | 'en' | 'ja'

export const translations: Record<Language, Record<string, string>> = {
  id: {
    // Navigation
    nav_beranda: 'Beranda Dojo',
    nav_rencana: 'Rencana Belajar',
    nav_reservasi: 'Reservasi Kelas',
    nav_kotoba: 'Setoran Kotoba',
    nav_kursus: 'Kursus Saya',
    nav_profil: 'Lihat Profil',
    nav_pengaturan: 'Pengaturan',
    nav_keluar: 'Keluar',

    // Common & Actions
    streak_days: 'Hari Streak',
    completed: 'Selesai',
    in_progress: 'Sedang Belajar',
    continue_learning: 'Lanjutkan Belajar',
    save_changes: 'Simpan Perubahan',
    close: 'Tutup',
    cancel: 'Batal',
    confirm: 'Konfirmasi',
    search: 'Cari...',

    // Dashboard Widgets
    dash_welcome: 'Selamat datang kembali',
    dash_subtitle: 'Mari lanjutkan perjalanan belajar bahasa Jepangmu hari ini! Setiap video yang kamu selesaikan adalah investasi terbaik untuk masa depanmu.',
    dash_enrolled_courses: 'Kursus Terdaftar',
    dash_streak_label: 'Streak Hari Ini',
    dash_completed_courses: 'Kursus Selesai',
    dash_daily_missions: 'Misi Harian Mandiri Hari Ini',
    dash_daily_missions_sub: 'Selesaikan target harian video, kuis, dan kotoba untuk mempertahankan streak!',
    dash_agenda_title: 'Jadwal & Agenda Saya',
    dash_agenda_sub: 'Linimasa Misi Harian & Kelas Live',
    dash_quick_shortcuts: 'Akses Pintas Cepat',
    dash_shortcut_kotoba: 'Jurnal Kosakata (Kotoba)',
    dash_shortcut_kotoba_sub: 'Catatan & Uji Hafalan',
    dash_shortcut_class: 'Reservasi Kelas Live / Offline',
    dash_shortcut_class_sub: 'Jadwal Zoom & Dojo',
    dash_course_progress: 'Progres Kursus Saya',
    dash_no_mission: 'Kamu belum membuat Misi Harian untuk hari ini.',
    dash_create_mission_btn: '+ Susun Misi Harian Sekarang →',
    dash_streak_habit: 'Pertahankan kebiasaan belajar harianmu!',
    dash_book_progress_title: 'Progress Belajar Buku',
    dash_book_progress_sub: 'Minna no Nihongo Jilid 1 & 2 (Bab 1 - 50)',
    dash_jilid_1_title: 'Jilid 1 (Dasar I)',
    dash_jilid_2_title: 'Jilid 2 (Dasar II)',
    dash_jilid_1_desc: 'Bab 1 s/d Bab 25 • 125 Video Materi',
    dash_jilid_2_desc: 'Bab 26 s/d Bab 50 • 125 Video Materi',
    dash_open_course_btn: 'Buka Kursus →',
    dash_action_watch: '▶ Lanjut Nonton',
    dash_action_quiz: '✏️ Mulai Kuis',
    dash_action_kotoba: '🔤 Buka Kotoba',

    // Learning Plan
    lp_title: 'Rencana Belajar & Kalender Misi',
    lp_subtitle: 'Klik pada tanggal di kalender untuk menyusun misi harian atau melihat arsip pembelajaran',
    lp_banner_guide_title: 'Panduan Praktis Rencana Belajar & Reservasi Kelas Live',
    lp_banner_guide_desc: 'Gunakan mode Kalender Grid untuk melihat ringkasan status bulanan, atau mode Agenda Schedule untuk menyusuri linimasa harian.',
    lp_tag_daily_mission: '🎯 Misi Rencana Harian (Wajib Setiap Hari)',
    lp_tag_online_class: '💻 Kelas Online (Batas 1 Sesi/Minggu)',
    lp_tag_offline_class: '🏢 Kelas Offline (Batas 1 Sesi/Bulan)',
    lp_stamp_legend_title: 'Cap Status Misi Mandiri (Tanggal Berlalu):',
    lp_btn_create: '+ Susun Misi Hari Ini',
    lp_tab_calendar: '📅 Kalender Grid',
    lp_tab_feed: '📋 Feed Agenda',
    lp_calendar_view: 'Kalender',
    lp_schedule_view: 'Agenda Schedule',
    lp_agenda_header: 'Agenda Jadwal Pembelajaran & Kelas Live',
    lp_only_activities: 'Hanya Hari Beragenda',
    lp_show_all_dates: 'Tampilkan Semua Tanggal',
    lp_archive_mode: 'Arsip Rencana Belajar',
    lp_target_missions: 'Target & Misi',
    lp_edit_mission_btn: '⚙️ Edit Misi Tanggal Ini',
    lp_past_date_locked: '🔒 Tanggal telah berlalu (Mode Lihat Arsip)',
    lp_stamp_passed: '100% Selesai',
    lp_stamp_incomplete: 'Belum Tuntas (<100%)',
    lp_stamp_noplan: 'Tidak Ada Rencana',
    lp_stamp_uncreated: 'Belum Buat Rencana',
    lp_modal_title: 'Susun Misi Belajar Mandiri',
    lp_target_date: 'Target Harian Tanggal:',
    lp_step1_video: '1. Pilih Video Materi (Minna no Nihongo)',
    lp_step2_replay: '2. Target Replay Video',
    lp_step3_quiz: '3. Target Kuis Evaluasi',
    lp_step4_kotoba: '4. Target Setoran Kotoba',
    lp_preset_relaxed: 'Santai (1 Video)',
    lp_preset_standard: 'Standar (2 Video)',
    lp_preset_intensive: 'Intensif (3 Video)',
    lp_clear_plan: 'Hapus Rencana',
    lp_save_mission: 'Simpan Misi Belajar',
    lp_today_btn: 'Hari Ini',

    // Class Reservation
    cr_title: 'Reservasi Kelas Online & Offline',
    cr_subtitle: 'Pilih hari dan jam terbaik untuk mengasah percakapan (Kaiwa) dengan instruktur.',
    cr_tag: 'Jadwal & Interaktif Class',
    cr_requirement: '*Wajib Mengambil Minimal 2 Kelas Online / Bulan',
    cr_requirement_sub: 'Untuk memastikan kemampuan percakapan Bahasa Jepang kamu terus terasah, setiap siswa diwajibkan mengikuti sekurang-kurangnya 2 sesi kelas online live per minggu/bulan.',
    cr_search_placeholder: 'Cari judul bab, materi, atau instruktur...',
    cr_tab_all: 'Semua Kelas',
    cr_tab_online: '💻 Kelas Online (Mingguan)',
    cr_tab_offline: '🏫 Kelas Offline (Bulanan)',
    cr_tab_my_booking: '📌 Jadwal Saya',
    cr_btn_book: 'Reservasi Kelas Ini',
    cr_btn_cancel: 'Batalkan Reservasi',
    cr_filter_week_label: 'Filter Minggu:',
    cr_all_weeks: 'Semua Minggu',
    cr_week_1: 'Minggu Ke-1',
    cr_week_2: 'Minggu Ke-2',
    cr_week_3: 'Minggu Ke-3',
    cr_week_4: 'Minggu Ke-4',
    cr_seats_left: 'Sisa Kursi:',
    cr_booked_badge: '✅ Terdaftar',

    // Setoran Kotoba
    sk_title: 'Jurnal Kosakata (Kotoba) Saya',
    sk_subtitle: 'Catat dan simpan setiap kosakata Bahasa Jepang baru yang kamu temukan. Uji hafalanmu secara berkala untuk menentukan kata yang sudah kamu kuasai!',
    sk_stat_total: 'Kosakata Tersimpan',
    sk_stat_mastered: 'Kosakata Dikuasai',
    sk_stat_pct: 'Tingkat Hafalan',
    sk_test_btn: '🧠 Uji Hafalan Kosakata',
    sk_add_btn: 'Tambah Kosakata Baru',
    sk_search_placeholder: 'Cari kanji, romaji, atau arti...',
    sk_mastered: '✅ Dikuasai',
    sk_unmastered: '⭕ Tandai Dikuasai',
    sk_input_japanese: 'Huruf Jepang (Kanji / Hiragana)',
    sk_input_japanese_ph: 'Contoh: 食べる (たべる)',
    sk_input_romaji: 'Cara Baca (Romaji)',
    sk_input_romaji_ph: 'Contoh: taberu',
    sk_input_meaning: 'Makna / Terjemahan',
    sk_input_meaning_ph: 'Contoh: Makan (Kata Kerja)',
    sk_input_image: 'URL Gambar (Opsional)',
    sk_input_image_ph: 'https://...',
    sk_guide_title: '💡 Panduan Menambah & Menguji Kosakata',
    sk_guide_hide: 'Sembunyikan ✕',
    sk_test_finish: '🎉 Uji Hafalan Selesai!',
    sk_test_mastered_btn: '🟢 Sudah Mudah / Dikuasai',
    sk_test_difficult_btn: '🔴 Masih Sulit',
    sk_test_check_answer: '🔑 Periksa Kunci Jawaban',

    // My Courses
    mc_title: 'Buku Kursus Minna no Nihongo',
    mc_subtitle: 'Pilih jilid buku dan pelajari 5 video materi + 1 kuis di setiap babnya',
    mc_search_placeholder: 'Cari judul bab atau materi...',
    mc_quiz_locked: 'Kuis Terkunci 🔒',
    mc_quiz_locked_msg: 'Kamu harus menonton seluruh 3 video materi pada bab ini terlebih dahulu sebelum dapat membuka Kuis Evaluasi ini!',
    mc_trivia_title: '⛩️ Japan Trivia & Fun Fact',
    mc_next_trivia: 'Fun Fact Selanjutnya',
    mc_lesson_video: 'Video Materi',
    mc_lesson_quiz: 'Kuis Evaluasi',
    mc_lesson_kotoba: 'Setoran Kotoba',
    mc_watched_times: 'Ditonton',
    mc_times: 'kali',
    bab_label: 'Bab',
    chapter_label: 'Bab',
    quiz_label: 'Kuis Evaluasi',
    part_label: 'Part',
    course_title_vol1: 'Bahasa Jepang Dasar (Jilid 1)',
    course_title_vol2: 'Bahasa Jepang Menengah (Jilid 2)',
    mc_quiz_locked_desc: 'Tonton video lagi untuk membuka',
    mc_kotoba_desc: 'Setoran Kosakata & Artinya',
    mc_quiz_desc: '10 Soal Pilihan Ganda',
    mc_video_prep_desc: 'Video sedang disiapkan',
    mc_video_desc: 'Materi Bahasa Jepang',
    mc_locked: 'Terkunci',
    mc_coming_soon: 'Segera Hadir',
    sk_stat_learning: 'Masih Dipelajari',
    sk_stat_memorization: 'Tingkat Hafalan',
    sk_filter_all: 'Semua',
    sk_filter_unmastered: '📖 Masih Dipelajari',
    sk_filter_mastered: '✅ Sudah Dikuasai',
    sk_badge_mastered: '✅ Dikuasai',
    sk_badge_learning: '📖 Masih Dipelajari',
    sk_badge_mark_mastered: '⭕ Tandai Dikuasai',
    sk_meaning_label: 'Makna / Arti:',

    // Profile
    pf_title: 'Profil Pengguna',
    pf_subtitle: 'Kelola informasi pribadi, statistik belajar, dan pencapaian lencana Anda',
    pf_role_student: '🎓 Pelajar KaiwaDoJo',
    pf_tab_overview: '👤 Ringkasan & Edit Profil',
    pf_tab_courses: '📚 Kursus Saya',
    pf_tab_achievements: '🏆 Pencapaian & Lencana',
    pf_tab_stats: '📊 Statistik & Aktivitas',
    pf_input_fullname: 'Nama Lengkap',
    pf_input_fullname_ph: 'Masukkan nama lengkap...',
    pf_input_username: 'Nama Pengguna (Username)',
    pf_input_username_ph: 'Masukkan username...',
    pf_input_bio: 'Biografi Singkat / Bio',
    pf_input_bio_ph: 'Tulis sepatah kata tentang motivasi belajar bahasa Jepangmu...',
    
    // Settings Page
    settings_title: 'Pengaturan Akun & Tampilan',
    settings_subtitle: 'Sesuaikan pengalaman belajar, preferensi tampilan, bahasa, dan keamanan akun Anda',
    theme_title: 'Tema Aplikasi (Light / Dark Mode)',
    theme_light: 'Terang (Light)',
    theme_dark: 'Gelap (Dark)',
    theme_system: 'Ikuti Sistem',
    text_size_title: 'Ukuran Teks Aplikasi',
    language_title: 'Bahasa Antarmuka Aplikasi',
    security_title: 'Keamanan & Ubah Kata Sandi',
    new_password: 'Kata Sandi Baru',
    confirm_password: 'Konfirmasi Kata Sandi Baru',
    pw_min_char: 'Minimal 6 karakter',
    pw_repeat_ph: 'Ulangi kata sandi baru',
    update_password: 'Perbarui Kata Sandi',
    danger_zone: 'Zona Bahaya',
    danger_desc: 'Menghapus akun Anda akan menghapus data profil, histori pembelajaran, dan progres streak secara permanen. Tindakan ini tidak dapat dibatalkan.',
    delete_account: 'Hapus Akun Saya',
    delete_modal_title: 'Konfirmasi Hapus Akun',
    delete_modal_prompt: 'Apakah Anda yakin ingin menghapus akun Anda? Semua data Anda akan dihapus secara permanen dari KaiwaDoJo.',
    delete_modal_instruction: 'Ketik HAPUS AKUN untuk mengonfirmasi:',
    delete_confirm_code: 'HAPUS AKUN',
    delete_confirm_btn: 'Ya, Hapus Permanen',

    // Toast Notifications
    lang_changed_id: 'Bahasa aplikasi berhasil diubah ke Bahasa Indonesia 🇮🇩',
    lang_changed_en: 'Language successfully updated to English 🇬🇧',
    lang_changed_ja: '言語が日本語に変更されました 🇯🇵',
  },
  en: {
    // Navigation
    nav_beranda: 'Dojo Home',
    nav_rencana: 'Learning Plan',
    nav_reservasi: 'Class Reservation',
    nav_kotoba: 'Vocabulary Journal',
    nav_kursus: 'My Courses',
    nav_profil: 'View Profile',
    nav_pengaturan: 'Settings',
    nav_keluar: 'Sign Out',

    // Common & Actions
    streak_days: 'Days Streak',
    completed: 'Completed',
    in_progress: 'In Progress',
    continue_learning: 'Continue Learning',
    save_changes: 'Save Changes',
    close: 'Close',
    cancel: 'Cancel',
    confirm: 'Confirm',
    search: 'Search...',

    // Dashboard Widgets
    dash_welcome: 'Welcome back',
    dash_subtitle: "Let's continue your Japanese learning journey today! Every lesson you complete is a great investment for your future.",
    dash_enrolled_courses: 'Enrolled Courses',
    dash_streak_label: 'Today Streak',
    dash_completed_courses: 'Completed Courses',
    dash_daily_missions: "Today's Self Daily Missions",
    dash_daily_missions_sub: 'Complete your daily video, quiz, and vocabulary targets to maintain your streak!',
    dash_agenda_title: 'My Schedule & Agenda',
    dash_agenda_sub: 'Timeline of Daily Missions & Live Classes',
    dash_quick_shortcuts: 'Quick Shortcuts',
    dash_shortcut_kotoba: 'Vocabulary Journal (Kotoba)',
    dash_shortcut_kotoba_sub: 'Notes & Flashcard Quiz',
    dash_shortcut_class: 'Live / Offline Class Reservation',
    dash_shortcut_class_sub: 'Zoom & Dojo Schedule',
    dash_course_progress: 'My Course Progress',
    dash_no_mission: "You haven't created a Daily Mission for today.",
    dash_create_mission_btn: '+ Create Daily Mission Now →',
    dash_streak_habit: 'Maintain your daily study habit!',
    dash_book_progress_title: 'Book Study Progress',
    dash_book_progress_sub: 'Minna no Nihongo Vol. 1 & 2 (Ch. 1 - 50)',
    dash_jilid_1_title: 'Vol. 1 (Basic I)',
    dash_jilid_2_title: 'Vol. 2 (Basic II)',
    dash_jilid_1_desc: 'Ch. 1 to Ch. 25 • 125 Video Lessons',
    dash_jilid_2_desc: 'Ch. 26 to Ch. 50 • 125 Video Lessons',
    dash_open_course_btn: 'Open Course →',
    dash_action_watch: '▶ Continue Watching',
    dash_action_quiz: '✏️ Start Quiz',
    dash_action_kotoba: '🔤 Open Vocabulary',

    // Learning Plan
    lp_title: 'Learning Plan & Mission Calendar',
    lp_subtitle: 'Click on any date to set daily study targets or review past learning records',
    lp_banner_guide_title: 'Practical Guide to Study Plans & Live Class Reservations',
    lp_banner_guide_desc: 'Use Grid Calendar mode for a monthly status overview, or Agenda Feed mode to browse daily timelines.',
    lp_tag_daily_mission: '🎯 Daily Plan Mission (Mandatory Daily)',
    lp_tag_online_class: '💻 Online Class (Max 1 Session/Week)',
    lp_tag_offline_class: '🏢 Offline Class (Max 1 Session/Month)',
    lp_stamp_legend_title: 'Self-Study Mission Stamp Status (Past Dates):',
    lp_btn_create: "+ Create Today's Mission",
    lp_tab_calendar: '📅 Calendar Grid',
    lp_tab_feed: '📋 Agenda Feed',
    lp_calendar_view: 'Calendar',
    lp_schedule_view: 'Agenda Schedule',
    lp_agenda_header: 'Learning & Live Class Agenda Timeline',
    lp_only_activities: 'Only Active Days',
    lp_show_all_dates: 'Show All Dates',
    lp_archive_mode: 'Study Plan Archives',
    lp_target_missions: 'Targets & Missions',
    lp_edit_mission_btn: '⚙️ Edit Mission for This Date',
    lp_past_date_locked: '🔒 Date has passed (Archive View Mode)',
    lp_stamp_passed: '100% Completed',
    lp_stamp_incomplete: 'Incomplete (<100%)',
    lp_stamp_noplan: 'No Plan Set',
    lp_stamp_uncreated: 'Plan Not Created',
    lp_modal_title: 'Create Self-Study Mission',
    lp_target_date: 'Daily Target Date:',
    lp_step1_video: '1. Select Lesson Video (Minna no Nihongo)',
    lp_step2_replay: '2. Target Video Replays',
    lp_step3_quiz: '3. Target Evaluation Quizzes',
    lp_step4_kotoba: '4. Target Vocabulary Entries',
    lp_preset_relaxed: 'Relaxed (1 Video)',
    lp_preset_standard: 'Standard (2 Videos)',
    lp_preset_intensive: 'Intensive (3 Videos)',
    lp_clear_plan: 'Clear Plan',
    lp_save_mission: 'Save Study Mission',
    lp_today_btn: 'Today',

    // Class Reservation
    cr_title: 'Live & Offline Class Reservation',
    cr_subtitle: 'Choose the best day and time to practice conversation (Kaiwa) with instructors.',
    cr_tag: 'Schedules & Interactive Classes',
    cr_requirement: '*Mandatory Requirement: Minimum 2 Online Classes / Month',
    cr_requirement_sub: 'To ensure your Japanese conversation skills continue to sharpen, each student is required to attend at least 2 live online sessions per month.',
    cr_search_placeholder: 'Search topic, material, or instructor...',
    cr_tab_all: 'All Classes',
    cr_tab_online: '💻 Online Class (Weekly)',
    cr_tab_offline: '🏫 Offline Class (Monthly)',
    cr_tab_my_booking: '📌 My Bookings',
    cr_btn_book: 'Book This Class',
    cr_btn_cancel: 'Cancel Booking',
    cr_filter_week_label: 'Filter Week:',
    cr_all_weeks: 'All Weeks',
    cr_week_1: 'Week 1',
    cr_week_2: 'Week 2',
    cr_week_3: 'Week 3',
    cr_week_4: 'Week 4',
    cr_seats_left: 'Seats Left:',
    cr_booked_badge: '✅ Registered',

    // Setoran Kotoba
    sk_title: 'My Vocabulary Journal (Kotoba)',
    sk_subtitle: 'Record and save every new Japanese vocabulary word you learn. Quiz yourself regularly to master them!',
    sk_stat_total: 'Saved Words',
    sk_stat_mastered: 'Mastered Words',
    sk_stat_pct: 'Retention Rate',
    sk_test_btn: '🧠 Flashcard Quiz Test',
    sk_add_btn: 'Add New Word',
    sk_search_placeholder: 'Search kanji, romaji, or meaning...',
    sk_mastered: '✅ Mastered',
    sk_unmastered: '⭕ Mark Mastered',
    sk_input_japanese: 'Japanese Characters (Kanji / Hiragana)',
    sk_input_japanese_ph: 'e.g. 食べる (たべる)',
    sk_input_romaji: 'Pronunciation (Romaji)',
    sk_input_romaji_ph: 'e.g. taberu',
    sk_input_meaning: 'Meaning / Translation',
    sk_input_meaning_ph: 'e.g. Eat (Verb)',
    sk_input_image: 'Image URL (Optional)',
    sk_input_image_ph: 'https://...',
    sk_guide_title: '💡 Guide to Adding & Testing Vocabulary',
    sk_guide_hide: 'Hide ✕',
    sk_test_finish: '🎉 Flashcard Quiz Completed!',
    sk_test_mastered_btn: '🟢 Mastered / Easy',
    sk_test_difficult_btn: '🔴 Still Difficult',
    sk_test_check_answer: '🔑 Check Answer Key',

    // My Courses
    mc_title: 'Minna no Nihongo Course Books',
    mc_subtitle: 'Select a volume and study 5 lesson videos + 1 quiz in each chapter',
    mc_search_placeholder: 'Search chapter title or topic...',
    mc_quiz_locked: 'Quiz Locked 🔒',
    mc_quiz_locked_msg: 'You must watch all 3 lesson videos in this chapter before unlocking this evaluation quiz!',
    mc_trivia_title: '⛩️ Japan Trivia & Fun Fact',
    mc_next_trivia: 'Next Fun Fact',
    mc_lesson_video: 'Video Lesson',
    mc_lesson_quiz: 'Evaluation Quiz',
    mc_lesson_kotoba: 'Vocabulary Journal',
    mc_watched_times: 'Watched',
    mc_times: 'times',
    bab_label: 'Chapter',
    chapter_label: 'Chapter',
    quiz_label: 'Evaluation Quiz',
    part_label: 'Part',
    course_title_vol1: 'Basic Japanese (Vol. 1)',
    course_title_vol2: 'Intermediate Japanese (Vol. 2)',
    mc_quiz_locked_desc: 'Watch more videos to unlock',
    mc_kotoba_desc: 'Vocabulary Entries & Meanings',
    mc_quiz_desc: '10 Multiple Choice Questions',
    mc_video_prep_desc: 'Video in preparation',
    mc_video_desc: 'Japanese Lesson Material',
    mc_locked: 'Locked',
    mc_coming_soon: 'Coming Soon',
    sk_stat_learning: 'Still Learning',
    sk_stat_memorization: 'Memorization Rate',
    sk_filter_all: 'All',
    sk_filter_unmastered: '📖 Still Learning',
    sk_filter_mastered: '✅ Mastered',
    sk_badge_mastered: '✅ Mastered',
    sk_badge_learning: '📖 Learning',
    sk_badge_mark_mastered: '⭕ Mark as Mastered',
    sk_meaning_label: 'Meaning / Translation:',

    // Profile
    pf_title: 'User Profile',
    pf_subtitle: 'Manage your personal information, study stats, and achievement badges',
    pf_role_student: '🎓 Kaiwa Student',
    pf_tab_overview: '👤 Overview & Edit Profile',
    pf_tab_courses: '📚 My Courses',
    pf_tab_achievements: '🏆 Achievements & Badges',
    pf_tab_stats: '📊 Stats & Activity',
    pf_input_fullname: 'Full Name',
    pf_input_fullname_ph: 'Enter full name...',
    pf_input_username: 'Username',
    pf_input_username_ph: 'Enter username...',
    pf_input_bio: 'Short Bio',
    pf_input_bio_ph: 'Write a brief line about your Japanese learning goals...',

    // Settings Page
    settings_title: 'Account & Display Settings',
    settings_subtitle: 'Customize your learning experience, theme, language, and account security',
    theme_title: 'App Theme (Light / Dark Mode)',
    theme_light: 'Light',
    theme_dark: 'Dark',
    theme_system: 'System Default',
    text_size_title: 'Text Size',
    language_title: 'Interface Language',
    security_title: 'Security & Change Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    pw_min_char: 'Minimum 6 characters',
    pw_repeat_ph: 'Repeat new password',
    update_password: 'Update Password',
    danger_zone: 'Danger Zone',
    danger_desc: 'Deleting your account will permanently remove profile data, study history, and streak progress. This action cannot be undone.',
    delete_account: 'Delete My Account',
    delete_modal_title: 'Confirm Account Deletion',
    delete_modal_prompt: 'Are you sure you want to delete your account? All your data will be permanently removed from KaiwaDoJo.',
    delete_modal_instruction: 'Type DELETE ACCOUNT to confirm:',
    delete_confirm_code: 'DELETE ACCOUNT',
    delete_confirm_btn: 'Yes, Delete Permanently',

    // Toast Notifications
    lang_changed_id: 'Language updated to Indonesian 🇮🇩',
    lang_changed_en: 'Language updated to English 🇬🇧',
    lang_changed_ja: 'Language updated to Japanese 🇯🇵',
  },
  ja: {
    // Navigation
    nav_beranda: '道場ホーム',
    nav_rencana: '学習計画',
    nav_reservasi: 'クラス予約',
    nav_kotoba: '単語帳 (Kotoba)',
    nav_kursus: '私のコース',
    nav_profil: 'プロフィール表示',
    nav_pengaturan: '設定',
    nav_keluar: 'ログアウト',

    // Common & Actions
    streak_days: '日連続達成',
    completed: '完了',
    in_progress: '学習中',
    continue_learning: '学習を続ける',
    save_changes: '変更を保存',
    close: '閉じる',
    cancel: 'キャンセル',
    confirm: '確認',
    search: '検索...',

    // Dashboard Widgets
    dash_welcome: 'おかえりなさい',
    dash_subtitle: '今日も日本語の学習を楽しく続けましょう！修了したレッスンは将来への素晴らしい投資です。',
    dash_enrolled_courses: '受講コース',
    dash_streak_label: '本日のストリーク',
    dash_completed_courses: '完了コース',
    dash_daily_missions: '本日の自主学習ミッション',
    dash_daily_missions_sub: '動画、クイズ、語彙の目標を達成して連続学習記録を維持しましょう！',
    dash_agenda_title: '私のスケジュール＆アジェンダ',
    dash_agenda_sub: '日次ミッション＆ライブクラスのタイムライン',
    dash_quick_shortcuts: 'クイックショートカット',
    dash_shortcut_kotoba: '単語帳 (Kotoba)',
    dash_shortcut_kotoba_sub: 'ノート＆暗記確認',
    dash_shortcut_class: 'ライブ・オフラインクラス予約',
    dash_shortcut_class_sub: 'Zoom＆道場日程',
    dash_course_progress: 'コース進捗状況',
    dash_no_mission: '本日の自主学習ミッションはまだ作成されていません。',
    dash_create_mission_btn: '＋ 今すぐ日次ミッションを作成 →',
    dash_streak_habit: '毎日の学習習慣を維持しましょう！',
    dash_book_progress_title: '書籍学習の進捗',
    dash_book_progress_sub: 'みんなの日本語 第1・2巻（第1〜50課）',
    dash_jilid_1_title: '第1巻（初級I）',
    dash_jilid_2_title: '第2巻（初級II）',
    dash_jilid_1_desc: '第1課〜第25課・125講義動画',
    dash_jilid_2_desc: '第26課〜第50課・125講義動画',
    dash_open_course_btn: 'コースを開く →',
    dash_action_watch: '▶ 視聴を続ける',
    dash_action_quiz: '✏️ クイズを開始',
    dash_action_kotoba: '🔤 単語帳を開く',

    // Learning Plan
    lp_title: '学習計画とミッションカレンダー',
    lp_subtitle: 'カレンダーの日付をクリックして毎日の学習目標を設定・確認しましょう',
    lp_banner_guide_title: '学習計画とライブクラス予約の実践ガイド',
    lp_banner_guide_desc: '月間状況の概要にはカレンダー表示を、日次の詳細なタイムラインにはアジェンダ表示をご利用ください。',
    lp_tag_daily_mission: '🎯 日次学習計画ミッション（毎日必須）',
    lp_tag_online_class: '💻 オンラインクラス（週1回上限）',
    lp_tag_offline_class: '🏢 オフラインクラス（月1回上限）',
    lp_stamp_legend_title: '自主学習ミッションスタンプ状態（過去の日付）：',
    lp_btn_create: '＋ 本日のミッションを作成',
    lp_tab_calendar: '📅 カレンダー表示',
    lp_tab_feed: '📋 アジェンダ表示',
    lp_calendar_view: 'カレンダー',
    lp_schedule_view: 'アジェンダ表示',
    lp_agenda_header: '学習スケジュール＆ライブクラスのアジェンダ',
    lp_only_activities: 'イベントのある日のみ',
    lp_show_all_dates: 'すべての日付を表示',
    lp_archive_mode: '学習計画アーカイブ',
    lp_target_missions: '目標＆ミッション',
    lp_edit_mission_btn: '⚙️ この日付のミッションを編集',
    lp_past_date_locked: '🔒 過去の日付（アーカイブ閲覧モード）',
    lp_stamp_passed: '100% 完了',
    lp_stamp_incomplete: '未完了 (<100%)',
    lp_stamp_noplan: '計画なし',
    lp_stamp_uncreated: '未作成',
    lp_modal_title: '自主学習ミッションを作成',
    lp_target_date: '日次目標設定日：',
    lp_step1_video: '1. 講義動画を選択（みんなの日本語）',
    lp_step2_replay: '2. 動画再生回数目標',
    lp_step3_quiz: '3. 評価クイズ目標',
    lp_step4_kotoba: '4. 単語提出目標',
    lp_preset_relaxed: 'ゆったり（1動画）',
    lp_preset_standard: '標準（2動画）',
    lp_preset_intensive: '集中（3動画）',
    lp_clear_plan: '計画を削除',
    lp_save_mission: '学習ミッションを保存',
    lp_today_btn: '今日',

    // Class Reservation
    cr_title: 'ライブ＆オフラインクラス予約',
    cr_subtitle: '講師と一緒に会話（Kaiwa）を練習する最適な日時を選択してください。',
    cr_tag: 'スケジュール＆対話型クラス',
    cr_requirement: '※必須条件：月2回以上のオンラインクラス受講が必要です',
    cr_requirement_sub: '日本語会話力を継続的に磨くため、すべての受講生は月に最低2回のライブオンラインクラスへの参加が義務付けられています。',
    cr_search_placeholder: 'トピック、教材、講師を検索...',
    cr_tab_all: '全クラス',
    cr_tab_online: '💻 オンラインクラス（週間）',
    cr_tab_offline: '🏫 オフラインクラス（月間）',
    cr_tab_my_booking: '📌 私の予約',
    cr_btn_book: 'このクラスを予約する',
    cr_btn_cancel: '予約をキャンセル',
    cr_filter_week_label: '週で絞り込み:',
    cr_all_weeks: 'すべての週',
    cr_week_1: '第1週',
    cr_week_2: '第2週',
    cr_week_3: '第3週',
    cr_week_4: '第4週',
    cr_seats_left: '残席数:',
    cr_booked_badge: '✅ 予約済み',

    // Setoran Kotoba
    sk_title: '私の単語帳（語彙提出）',
    sk_subtitle: '新しく学んだ日本語の単語を記録・保存しましょう。定期的に暗記テストを行って習得状況を確認できます！',
    sk_stat_total: '保存された単語',
    sk_stat_mastered: '習得済みの単語',
    sk_stat_pct: '記憶定着率',
    sk_test_btn: '🧠 暗記確認テスト',
    sk_add_btn: '新しい単語を追加',
    sk_search_placeholder: '漢字、ローマ字、意味を検索...',
    sk_mastered: '✅ 習得済み',
    sk_unmastered: '⭕ 習得済みにする',
    sk_input_japanese: '日本語の文字（漢字・ひらがな）',
    sk_input_japanese_ph: '例: 食べる (たべる)',
    sk_input_romaji: '読み方（ローマ字）',
    sk_input_romaji_ph: '例: taberu',
    sk_input_meaning: '意味・翻訳',
    sk_input_meaning_ph: '例: 食べる（動詞）',
    sk_input_image: '画像URL（任意）',
    sk_input_image_ph: 'https://...',
    sk_guide_title: '💡 単語追加・テスト利用ガイド',
    sk_guide_hide: '非表示 ✕',
    sk_test_finish: '🎉 単語テスト完了！',
    sk_test_mastered_btn: '🟢 習得済み・簡単',
    sk_test_difficult_btn: '🔴 まだ難しい',
    sk_test_check_answer: '🔑 解答を確認',

    // My Courses
    mc_title: 'みんなの日本語コース教材',
    mc_subtitle: '巻を選択し、各章5つの講義動画と1つのクイズを学習しましょう',
    mc_search_placeholder: '章のタイトルやトピックを検索...',
    mc_quiz_locked: 'クイズはロックされています 🔒',
    mc_quiz_locked_msg: 'この章の全3つの講義動画をすべて視聴するまで、評価クイズを開くことはできません！',
    mc_trivia_title: '⛩️ 日本の豆知識＆トリビア',
    mc_next_trivia: '次の豆知識',
    mc_lesson_video: '講義動画',
    mc_lesson_quiz: '評価クイズ',
    mc_lesson_kotoba: '単語提出',
    mc_watched_times: '視聴済み',
    mc_times: '回',
    bab_label: '第',
    chapter_label: '課',
    quiz_label: '評価クイズ',
    part_label: 'パート',
    course_title_vol1: '初級日本語（第1巻）',
    course_title_vol2: '中級日本語（第2巻）',
    mc_quiz_locked_desc: '動画をさらに視聴してロック解除',
    mc_kotoba_desc: '単語と意味の一覧',
    mc_quiz_desc: '4択クイズ10問',
    mc_video_prep_desc: '動画準備中',
    mc_video_desc: '日本語学習教材',
    mc_locked: 'ロック中',
    mc_coming_soon: '近日公開',
    sk_stat_learning: '学習中の単語',
    sk_stat_memorization: '暗記達成率',
    sk_filter_all: 'すべて',
    sk_filter_unmastered: '📖 学習中',
    sk_filter_mastered: '✅ 習得済み',
    sk_badge_mastered: '✅ 習得済み',
    sk_badge_learning: '📖 学習中',
    sk_badge_mark_mastered: '⭕ 習得済みにする',
    sk_meaning_label: '意味・訳語：',

    // Profile
    pf_title: 'ユーザープロフィール',
    pf_subtitle: '個人情報、学習統計、成果バッジを管理します',
    pf_role_student: '🎓 会話生',
    pf_tab_overview: '👤 概要とプロフ編集',
    pf_tab_courses: '📚 私のコース',
    pf_tab_achievements: '🏆 成果とバッジ',
    pf_tab_stats: '📊 統計とアクティビティ',
    pf_input_fullname: '氏名',
    pf_input_fullname_ph: '氏名を入力...',
    pf_input_username: 'ユーザー名',
    pf_input_username_ph: 'ユーザー名を入力...',
    pf_input_bio: '自己紹介',
    pf_input_bio_ph: '日本語学習の目標や意気込みをご記入ください...',

    // Settings Page
    settings_title: 'アカウントと画面設定',
    settings_subtitle: '学習環境、テーマ、言語、セキュリティ設定をカスタマイズします',
    theme_title: 'アプリテーマ（ライト/ダーク）',
    theme_light: 'ライト',
    theme_dark: 'ダーク',
    theme_system: 'システムに従う',
    text_size_title: '文字サイズ',
    language_title: '表示言語',
    security_title: 'セキュリティとパスワード変更',
    new_password: '新しいパスワード',
    confirm_password: '新しいパスワードの確認',
    pw_min_char: '最低6文字',
    pw_repeat_ph: '新しいパスワードを再入力',
    update_password: 'パスワードを更新',
    danger_zone: 'デンジャーゾーン',
    danger_desc: 'アカウントを削除すると、プロフィールデータ、学習履歴、ストリーク進捗が永久に消去されます。この操作は取り消せません。',
    delete_account: 'アカウントを削除',
    delete_modal_title: 'アカウント削除の確認',
    delete_modal_prompt: '本当にアカウントを削除しますか？すべてのデータはKaiwaDoJoから永久に削除されます。',
    delete_modal_instruction: '確認のため「DELETE ACCOUNT」と入力してください：',
    delete_confirm_code: 'DELETE ACCOUNT',
    delete_confirm_btn: 'はい、永久削除します',

    // Toast Notifications
    lang_changed_id: '言語をインドネシア語に変更しました 🇮🇩',
    lang_changed_en: '言語を英語に変更しました 🇬🇧',
    lang_changed_ja: '言語を日本語に変更しました 🇯🇵',
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, fallback?: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('kaiwa_language') as Language) || 'id'
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('kaiwa_language', lang)
    window.dispatchEvent(new Event('kaiwa-language-change'))
  }

  useEffect(() => {
    const handleLanguageEvent = () => {
      const stored = (localStorage.getItem('kaiwa_language') as Language) || 'id'
      if (stored !== language) {
        setLanguageState(stored)
      }
    }
    window.addEventListener('kaiwa-language-change', handleLanguageEvent)
    return () => window.removeEventListener('kaiwa-language-change', handleLanguageEvent)
  }, [language])

  const t = (key: string, fallback?: string): string => {
    return translations[language]?.[key] || translations['id']?.[key] || fallback || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
